version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer
    networks:
      - backend

  sonarqube:
    image: sonarqube:8.9.7-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - backend

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    networks:
      - backend

  app:
    build: .
    container_name: foyer-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyer?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8086:8086"
    networks:
      - backend

networks:
  backend:
